version: "3.9"

services:
  db:
    image: postgres:17
    container_name: snowops-anpr-db
    environment:
      POSTGRES_DB: snowops_anpr
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: snowops-anpr-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      APP_ENV: "development"
      HTTP_HOST: "0.0.0.0"
      HTTP_PORT: "8080"
      DB_DSN: "postgres://postgres:postgres@db:5432/snowops_anpr?sslmode=disable"
      JWT_ACCESS_SECRET: "supersecret"
      CAMERA_RTSP_URL: "rtsp://admin:SnowCam1!@194.26.239.249:554/Streaming/Channels/101"
      CAMERA_HTTP_HOST: "http://194.26.239.249"
      CAMERA_MODEL: "DS-TCG406-E"
      HIK_CONNECT_DOMAIN: "litedev.hik-connect.com"
      ENABLE_SNOW_VOLUME_ANALYSIS: "false"
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  db_data: {}

